### ISSUE TITLE
NewDefaultLayout ignores component settings

### ISSUE THREAD

**Issue by brollb** [rosmod/webgme-rosmod#116]
`NewDefaultLayout` ignores component settings for it's panels: https://github.com/rosmod/webgme-rosmod/blob/master/src/layouts/NewDefaultLayout/NewDefaultLayout.js#L27

It would be nice if it used the component settings so it was able to be used in other projects as well. If you decide against that, the config in the components.json should be removed: https://github.com/rosmod/webgme-rosmod/blob/master/config/components.json#L185-L224

**Comment by finger563** [comment]
Good point; I'll update it for that and then make it its own repo.

**Comment by finger563** [comment]
@brollb can you verify that c5dea6a is what you were intending?

**Comment by brollb** [comment]
Yep, that's what I was thinking!  Thanks!
