### ISSUE TITLE
plotly error

### ISSUE THREAD

**Issue by DWatkins** [rosmod/webgme-rosmod#150]
![image](https://user-images.githubusercontent.com/455381/27966619-79173bb0-6305-11e7-8f8f-05e87f604d6b.png)

**Comment by DWatkins** [comment]
![image](https://user-images.githubusercontent.com/455381/27967018-1200b9ae-6307-11e7-9fcc-e77c0327cef4.png)

**Comment by finger563** [comment]
Looks like it might be related to a plotly issue.  Please provide a description of what you're doing that reproduces this so I can confirm.

**Comment by finger563** [comment]
closing for now, haven't seen this in a while so I assume a plotly update has fixed it.
