### ISSUE TITLE
Modify Run/Stop Experiment to properly setup/teardown definitions

### ISSUE THREAD

**Issue by DWatkins** [rosmod/webgme-rosmod#185]
Need to copy over python msg/srv definitions and package manifest (`package.xml`) to all hosts and add them to `PYTHONPATH` and `ROS_PACKAGE_PATH` respectively.

If they're located in the experiment folder, should already be removed automatically

**Comment by finger563** [comment]
related to #184

**Comment by DWatkins** [comment]
Is there a need to copy message definitions to ALL hosts?  If the purpose of this is for rosbridge integration, only the rosbridge instance needs the definitions.

**Comment by finger563** [comment]
since they don't need to be copied to all hosts, i'm closing this a a duplicate of #186
