### ISSUE TITLE
Spawn rosbridge in new shell to connect to a roscore

### ISSUE THREAD

**Issue by DWatkins** [rosmod/webgme-rosmod#186]
_From @DWatkins on November 2, 2017 17:4_

Spawn a worker process to contain rosbridge and roslib interfaces for each roscore.

Rosbridge needs to run in a new shell for each roscore. 

Needs to:
1. source message definitions for all packages on the system
2. generate a unique port to reside on 

_Copied from original issue: rosmod/rosmct#2_

**Comment by DWatkins** [comment]
only spawn a new shell for rosbridge to reside at.

**Comment by DWatkins** [comment]
updated to be on rosmod's end.  no long need to deal with roslib interaction, which is handled in rosmct

**Comment by DWatkins** [comment]
related to #182, #184, #185, #187

**Comment by finger563** [comment]
Need to figure out how to properly manage rosbridge_server's lifecycle (so we can kill it when we `StopExperiment`)

**Comment by DWatkins** [comment]
ocal host also needs to export ROS_IP to the ip address reachable by hosts in the system. Need for roscore to arbitrate pub/sub advertisements correctly

**Comment by finger563** [comment]
Will have to update the plugin so that the plugin can know by what IP the ROSMOD system can reach the rosmod server (esp. since the server can and usually does have more than one set of IP addresses)
