### ISSUE TITLE
Add new attribute to the externl node in the deployment so that the name attribute can be used to provide unique names for external nodes of the same type

### ISSUE THREAD

**Issue by DWatkins** [rosmod/webgme-rosmod#217]
example: running multiple realsense cameras at the same time

**Comment by finger563** [comment]
Did we determine that we can really do this? Isn't it dependent on the launch files themselves?

**Comment by finger563** [comment]
I believe this can be closed as solved by #218, closing for now.

**Comment by DWatkins** [comment]
#223 makes this more relevant again

![image](https://user-images.githubusercontent.com/455381/38054627-2210767a-329d-11e8-8f86-7ba69a5b87b4.png)
