### ISSUE TITLE
Cannot use rosmsg show for custom topic

### ISSUE THREAD

**Issue by DWatkins** [rosmod/webgme-rosmod#227]
Maybe need to add the `src` folder to a path somewhere? I will investigate further.

**Comment by finger563** [comment]
currently only way i've gotten it to work is to source the `devel/setup.zsh` that's generated - we may need to copy that over in order to be able to do this...

**Comment by finger563** [comment]
it's weird because `roscd` `rostopic echo` and such all work just fine

**Comment by DWatkins** [comment]
what is the full value of ROS_ROOT and PYTHONPATH? 






On Thu, Mar 22, 2018 at 8:36 PM -0500, "William Emfinger" <notifications@github.com> wrote:












it's weird because roscd rostopic echo and such all work just fine

**Comment by DWatkins** [comment]
one issue is there are no `.msg` files in the the generated `share` folder. Copying a the .msg from the `src` folder doesn't fix the problem, so something else is messing up too.

**Comment by DWatkins** [comment]
also need to copy the `cmake` folder from `devel/share/[package name]` to the `share` folder in rosmod's generated folder

`cp -rL` to deference symbolic links

moving cmake folder and the `.msg` file fixes the problem
