### ISSUE TITLE
Compilation device priority

### ISSUE THREAD

**Issue by jeholliday** [rosmod/webgme-rosmod#246]
It would be useful if devices could be assigned a compilation priority, so that a more powerful device would always be used to compile if it's available.

**Comment by finger563** [comment]
I'll add a `sortable` widget to the config where you can specify the priority at compile time - this helps keep the system models fully separate (like they currently are)  You'll simply need to drag and drop the host that you want to preferentially compile on to the top of each list (where each list corresponds to the architecture + device ID)
