### ISSUE TITLE
Need a way to specify in the metamodel which user to deploy an experiment as

### ISSUE THREAD

**Issue by pranav-srinivas-kumar** [rosmod/webgme-rosmod#42]
We currently have no way to specify in the model which user to deplpy an experiment as -- ROSMOD always chooses the first available user.

**Comment by finger563** [comment]
Difficult w.r.t. how the user should specify this information: plugin doesn't have access to data during config time (and might be cumbersome) and the experiment only has pointers to the deployment and the system, the map between the two is generated on the fly (and is where the user specification would need to take place).  Additionally, all processes on a host are currently mapped and run as the same user.

**Comment by finger563** [comment]
Dependent on the implementation of https://github.com/webgme/webgme/issues/945
