### ISSUE TITLE
Integration execution plotting onto WebGME Experiment Plugin

### ISSUE THREAD

**Issue by pranav-srinivas-kumar** [rosmod/webgme-rosmod#45]
Add an attribute in the Results object that saves the contents of the retrieved plot and prepare a visualizer; one that displays the plot of the execution when clicked.

**Comment by finger563** [comment]
Closed by addition of ResultsViz visualizer in https://github.com/rosmod/webgme-rosmod/commit/1c3640d2fc1d87499ad1dbd6e12a8750c0ae6247
