### ISSUE TITLE
Experiments should have the ability to drag and drop objects onto its icon

### ISSUE THREAD

**Issue by DWatkins** [rosmod/webgme-rosmod#52]
Experiments should exhibit the same click and drag behavior seen in a subscriber port object, so that a deployment or system can be dragged onto a region of the experiment icon to create a pointer to that object.

**Comment by finger563** [comment]
This will be updated in a new visualizer; for now you can create an experiment by dragging a deployment or a system into the experiments aspect and it will automatically set the relevant pointer.  the other pointer will need to be set manually.

**Comment by finger563** [comment]
Alternatively, this will automatically work when https://github.com/webgme/webgme/issues/954 is completed.

**Comment by finger563** [comment]
SVGDecorator was updated to close webgme/webgme#954; closes this issue as well.
